In [2]:
import os
os.getcwd()

'c:\\Users\\82106\\OneDrive\\바탕 화면\\seoul_bicycle\\notebooks'

In [3]:
import glob

files = glob.glob("../data/raw/2025_0[4-6]/*.xlsx")
files

[]

In [4]:
import os

os.listdir("../data/raw")

['2025_04', '2025_05', '2025_06']

In [5]:
import os
os.listdir("../data/raw/2025_04")

['tpss_bcycl_od_statnhm_20250401.csv',
 'tpss_bcycl_od_statnhm_20250402.csv',
 'tpss_bcycl_od_statnhm_20250403.csv',
 'tpss_bcycl_od_statnhm_20250404.csv',
 'tpss_bcycl_od_statnhm_20250405.csv',
 'tpss_bcycl_od_statnhm_20250406.csv',
 'tpss_bcycl_od_statnhm_20250407.csv',
 'tpss_bcycl_od_statnhm_20250408.csv',
 'tpss_bcycl_od_statnhm_20250409.csv',
 'tpss_bcycl_od_statnhm_20250410.csv',
 'tpss_bcycl_od_statnhm_20250411.csv',
 'tpss_bcycl_od_statnhm_20250412.csv',
 'tpss_bcycl_od_statnhm_20250413.csv',
 'tpss_bcycl_od_statnhm_20250414.csv',
 'tpss_bcycl_od_statnhm_20250415.csv',
 'tpss_bcycl_od_statnhm_20250416.csv',
 'tpss_bcycl_od_statnhm_20250417.csv',
 'tpss_bcycl_od_statnhm_20250418.csv',
 'tpss_bcycl_od_statnhm_20250419.csv',
 'tpss_bcycl_od_statnhm_20250420.csv',
 'tpss_bcycl_od_statnhm_20250421.csv',
 'tpss_bcycl_od_statnhm_20250422.csv',
 'tpss_bcycl_od_statnhm_20250423.csv',
 'tpss_bcycl_od_statnhm_20250424.csv',
 'tpss_bcycl_od_statnhm_20250425.csv',
 'tpss_bcycl_od_statnhm_20250426.csv',
 'tpss_bcycl_od_statnhm_20250427.csv',
 'tpss_bcycl_od_statnhm_20250428.csv',
 'tpss_bcycl_od_statnhm_20250429.csv',
 'tpss_bcycl_od_statnhm_20250430.csv']

In [6]:
import glob
import pandas as pd

files = glob.glob("../data/raw/2025_0[4-6]/*.csv")
len(files)

91

In [7]:
import glob

files = glob.glob("../data/raw/2025_04/*.csv")
len(files)

30

In [8]:
import os
os.listdir("../data/raw")

['2025_04', '2025_05', '2025_06']

In [9]:
os.listdir("../data/raw/2025_04")[:5]

['tpss_bcycl_od_statnhm_20250401.csv',
 'tpss_bcycl_od_statnhm_20250402.csv',
 'tpss_bcycl_od_statnhm_20250403.csv',
 'tpss_bcycl_od_statnhm_20250404.csv',
 'tpss_bcycl_od_statnhm_20250405.csv']

In [10]:
import glob
glob.glob("../data/raw/2025_04/*.csv")[:5]

['../data/raw/2025_04\\tpss_bcycl_od_statnhm_20250401.csv',
 '../data/raw/2025_04\\tpss_bcycl_od_statnhm_20250402.csv',
 '../data/raw/2025_04\\tpss_bcycl_od_statnhm_20250403.csv',
 '../data/raw/2025_04\\tpss_bcycl_od_statnhm_20250404.csv',
 '../data/raw/2025_04\\tpss_bcycl_od_statnhm_20250405.csv']

In [11]:
import glob

files = glob.glob("../data/raw/2025_0[4-6]/*.csv")
len(files)

91

In [12]:
import glob
import pandas as pd

files = sorted(glob.glob("../data/raw/2025_0[4-6]/*.csv"))

df_list = []

for f in files:
    df = pd.read_csv(f, encoding="cp949")
    df_list.append(df)

bicycle = pd.concat(df_list, ignore_index=True)

bicycle.shape

# 행 개수 21255255 컬럼 개수 10 월별, 일별 다 concat으로 합침

(21255255, 10)

In [13]:
bicycle.columns

Index(['기준_날짜', '집계_기준', '기준_시간대', '시작_대여소_ID', '시작_대여소명', '종료_대여소_ID',
       '종료_대여소명', '전체_건수', '전체_이용_분', '전체_이용_거리'],
      dtype='object')

In [14]:
bicycle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21255255 entries, 0 to 21255254
Data columns (total 10 columns):
 #   Column     Dtype
---  ------     -----
 0   기준_날짜      int64
 1   집계_기준      object
 2   기준_시간대     int64
 3   시작_대여소_ID  object
 4   시작_대여소명    object
 5   종료_대여소_ID  object
 6   종료_대여소명    object
 7   전체_건수      int64
 8   전체_이용_분    float64
 9   전체_이용_거리   float64
dtypes: float64(2), int64(3), object(5)
memory usage: 1.6+ GB

In [15]:
bicycle["date"] = pd.to_datetime(
    bicycle["기준_날짜"].astype(str), format = "%Y%m%d"
)

In [16]:
bicycle[["기준_날짜", "date"]].head()

      기준_날짜       date
0  20250401 2025-04-01
1  20250401 2025-04-01
2  20250401 2025-04-01
3  20250401 2025-04-01
4  20250401 2025-04-01

In [17]:
bicycle["month"] = bicycle["date"].dt.month
bicycle["weekday"] = bicycle["date"].dt.weekday

In [18]:
bicycle["start_hour"] = bicycle["기준_시간대"] // 100
bicycle["start_minute"] = bicycle["기준_시간대"] % 100

In [19]:
cat_cols = [
    "집계_기준", "시작_대여소_ID", "시작_대여소명", "종료_대여소_ID", "종료_대여소명"
]

for c in cat_cols:
    bicycle[c] = bicycle[c].astype("category")

# 2천만건 이상의 대규모 데이터를 다루면서 분석 과부하를 방지하기 위해 문자열 컬럼을 category 타입으로 변환함
# 메모리 사용량과 처리 속도를 최적화함

In [20]:
bicycle.head()

,기준_날짜,집계_기준,기준_시간대,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,date,month,weekday,start_hour,start_minute
0,20250401,출발시간,1800,ST-2643,여의동_002_7,ST-277,양평2동_017_1,1,15.0,3120.0,2025-04-01,4,1,18,0
1,20250401,출발시간,855,ST-744,내곡동_007_3,ST-742,내곡동_006_3,1,4.0,910.0,2025-04-01,4,1,8,55
2,20250401,출발시간,1955,ST-1441,보광동_028_1,ST-1341,용문동_003_1,1,33.0,3907.0,2025-04-01,4,1,19,55
3,20250401,출발시간,2220,ST-1002,목1동_006_1,ST-3089,신정7동_003_1,1,14.0,2634.0,2025-04-01,4,1,22,20
4,20250401,출발시간,1455,ST-1122,"상계3,4동_047_1",ST-2710,상계8동_002_1,1,146.0,3682.0,2025-04-01,4,1,14,55

In [21]:
weekday_map = {
    0: 'Mon', 1: 'Tue', 2: 'Wed', 3: 'Thu', 4: 'Fri', 5: 'Sat', 6: 'Sun'
}

bicycle['weekday_name'] = bicycle['weekday'].map(weekday_map).astype('category')

In [22]:
bicycle['is_commute'] = (
    ((bicycle['start_hour'].between(7,9)) |
     (bicycle['start_hour'].between(18,20)))
     & (bicycle['weekday'] < 5)
)

In [23]:
bicycle.head()

,기준_날짜,집계_기준,기준_시간대,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,date,month,weekday,start_hour,start_minute,weekday_name,is_commute
0,20250401,출발시간,1800,ST-2643,여의동_002_7,ST-277,양평2동_017_1,1,15.0,3120.0,2025-04-01,4,1,18,0,Tue,True
1,20250401,출발시간,855,ST-744,내곡동_007_3,ST-742,내곡동_006_3,1,4.0,910.0,2025-04-01,4,1,8,55,Tue,True
2,20250401,출발시간,1955,ST-1441,보광동_028_1,ST-1341,용문동_003_1,1,33.0,3907.0,2025-04-01,4,1,19,55,Tue,True
3,20250401,출발시간,2220,ST-1002,목1동_006_1,ST-3089,신정7동_003_1,1,14.0,2634.0,2025-04-01,4,1,22,20,Tue,False
4,20250401,출발시간,1455,ST-1122,"상계3,4동_047_1",ST-2710,상계8동_002_1,1,146.0,3682.0,2025-04-01,4,1,14,55,Tue,False

In [24]:
holidays = [
    '2025-05-05',  # 어린이날 + 석가탄신일
    '2025-05-06',  # 어린이날 대체 공휴일
    '2025-06-03',  # 대통령선거 임시 공휴일
    '2025-06-06'   # 현충일
] 

# 법정 공휴일만 공휴일로 처리 (근로자의 날은 제외)

holidays = pd.to_datetime(holidays) 

# 여기까지가 공휴일만 뽑아 to_datetime

bicycle['is_holiday'] = bicycle['date'].isin(holidays)
bicycle['is_weekend'] = bicycle['weekday'] >= 5 # 토일 라벨링 56을 주말로 지정
bicycle['is_workday'] = (~bicycle['is_weekend']) & (~bicycle['is_holiday'])

In [25]:
bicycle.head()

,기준_날짜,집계_기준,기준_시간대,시작_대여소_ID,시작_대여소명,종료_대여소_ID,종료_대여소명,전체_건수,전체_이용_분,전체_이용_거리,date,month,weekday,start_hour,start_minute,weekday_name,is_commute,is_holiday,is_weekend,is_workday
0,20250401,출발시간,1800,ST-2643,여의동_002_7,ST-277,양평2동_017_1,1,15.0,3120.0,2025-04-01,4,1,18,0,Tue,True,False,False,True
1,20250401,출발시간,855,ST-744,내곡동_007_3,ST-742,내곡동_006_3,1,4.0,910.0,2025-04-01,4,1,8,55,Tue,True,False,False,True
2,20250401,출발시간,1955,ST-1441,보광동_028_1,ST-1341,용문동_003_1,1,33.0,3907.0,2025-04-01,4,1,19,55,Tue,True,False,False,True
3,20250401,출발시간,2220,ST-1002,목1동_006_1,ST-3089,신정7동_003_1,1,14.0,2634.0,2025-04-01,4,1,22,20,Tue,False,False,False,True
4,20250401,출발시간,1455,ST-1122,"상계3,4동_047_1",ST-2710,상계8동_002_1,1,146.0,3682.0,2025-04-01,4,1,14,55,Tue,False,False,False,True

In [26]:
bicycle.isnull().sum()

기준_날짜                0
집계_기준                0
기준_시간대               0
시작_대여소_ID            0
시작_대여소명          19657
종료_대여소_ID            0
종료_대여소명         114409
전체_건수                0
전체_이용_분         671726
전체_이용_거리        671726
date                 0
month                0
weekday              0
start_hour           0
start_minute         0
weekday_name         0
is_commute           0
is_holiday           0
is_weekend           0
is_workday           0
dtype: int64

In [ ]:
bicycle.to_csv(
    '../data/processed/bicycle_2025_04_06_cleaned.csv',
    index=False,
    encoding='utf-8-sig'
)

# bicycle 데이터 전처리한 거 상위폴더 data/processed로 옮기기
# 파일명과 폴더명은 전처리로 같은 의미지만 같은 이름을 방지하기 위해
# processed cleaned로 함

In [30]:
bicycle.sample(10000).to_csv(
    '../data/processed/bicycle_sample.csv',
    index=False,
    encoding='utf-8-sig'
)